name: supernova_translator
description: Supernova's translator task

version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.5
  chopper: ^3.0.6
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  provider: ^5.0.0
  copy_with_extension: ^1.4.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.4
  json_serializable: 3.5.1
  chopper_generator: ^3.0.6
  copy_with_extension_gen: ^1.4.0
  flutter_launcher_icons: ^0.8.0

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.jpg"